import datetime
import hashlib
import hmac
import os
import secrets
import smtplib
from email.mime.text import MIMEText

import extra_streamlit_components as stx
import streamlit as st


AUTH_COOKIE_NAME = "apollo_somaiya_session"
ALLOWED_EMAIL_DOMAIN = "@somaiya.edu"


def get_secret(name: str, default: str = "") -> str:
    try:
        return st.secrets.get(name, os.getenv(name, default))
    except Exception:
        return os.getenv(name, default)


def _get_signing_secret() -> bytes:
    """Retrieve secret key for signing session tokens."""
    secret = (
        get_secret("AUTH_SECRET")
        or get_secret("EMAIL_PASSWORD")
        or "apollo_omni_fallback_secret_key"
    )
    return secret.encode("utf-8")


def create_session_token(email: str) -> str:
    """Create an HMAC-SHA256 signed token for the user email."""
    normalized_email = email.strip().lower()
    signature = hmac.new(
        _get_signing_secret(),
        normalized_email.encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()
    return f"{normalized_email}:{signature}"


def verify_session_token(token: str | None) -> bool:
    """Verify HMAC signature to ensure the session cookie was generated by this server."""
    if not token or ":" not in token:
        return False

    email, _ = token.split(":", 1)
    if not is_allowed_email(email):
        return False

    expected_token = create_session_token(email)
    return hmac.compare_digest(token, expected_token)


def is_allowed_email(email: str) -> bool:
    return email.strip().lower().endswith(ALLOWED_EMAIL_DOMAIN)


def send_otp_email(target_email: str, otp_code: str):
    try:
        sender_email = get_secret("EMAIL_SENDER")
        sender_pass = get_secret("EMAIL_PASSWORD")
        if not sender_email or not sender_pass:
            return False, "Email credentials missing in Streamlit secrets."

        msg = MIMEText(
            f"Your Apollo Omni AI secure access code is: {otp_code}\n\n"
            "If you did not request this, please ignore this email."
        )
        msg["Subject"] = "APOLLO OMNI - Access Code"
        msg["From"] = sender_email
        msg["To"] = target_email

        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(sender_email, sender_pass)
            server.send_message(msg)
        return True, "Success"
    except Exception as exc:
        return False, str(exc)


def require_authentication(cookie_manager: stx.CookieManager) -> None:
    st.session_state.setdefault("otp_sent", False)
    st.session_state.setdefault("generated_otp", None)
    st.session_state.setdefault("user_email", "")

    cookies = cookie_manager.get_all()

    # Wait for stx.CookieManager JS component to initialize completely
    if cookies is None:
        st.stop()

    if "authenticated" not in st.session_state:
        cookie_val = cookies.get(AUTH_COOKIE_NAME)
        st.session_state.authenticated = verify_session_token(cookie_val)

    if st.session_state.authenticated:
        return

    st.markdown(
        "<div style='text-align:center;margin-top:80px;'><h2 style='color:#f97316;'>Restricted Access</h2>"
        "<p style='color:#a1a1aa;'>Verify your Somaiya university email to receive a secure access code.</p></div>",
        unsafe_allow_html=True,
    )
    _, col_login, _ = st.columns([3, 4, 3])
    with col_login:
        st.markdown("<div class='cyber-card'>", unsafe_allow_html=True)
        if not st.session_state.otp_sent:
            email_input = st.text_input("University Email", placeholder="your.name@somaiya.edu")
            if st.button("Send access code", use_container_width=True):
                if not is_allowed_email(email_input):
                    st.error("Access denied. Only @somaiya.edu accounts are permitted.")
                else:
                    with st.status("Sending secure code...", expanded=False) as status:
                        # Cryptographically secure 6-digit OTP
                        otp = f"{secrets.randbelow(900000) + 100000}"
                        st.session_state.generated_otp = otp
                        st.session_state.user_email = email_input.strip().lower()
                        success, error_msg = send_otp_email(st.session_state.user_email, otp)
                        if success:
                            st.session_state.otp_sent = True
                            status.update(label="Code sent.", state="complete")
                            st.rerun()
                        else:
                            status.update(label="Email failed.", state="error")
                            st.error(error_msg)
        else:
            st.success(f"Secure code sent to {st.session_state.user_email}")
            otp_input = st.text_input("Enter 6-digit code", type="password")
            if st.button("Verify and enter", use_container_width=True):
                if otp_input.strip() == st.session_state.generated_otp:
                    st.session_state.authenticated = True

                    # Generate and set HMAC signed token
                    token = create_session_token(st.session_state.user_email)
                    cookie_manager.set(
                        AUTH_COOKIE_NAME,
                        token,
                        expires_at=datetime.datetime.now() + datetime.timedelta(days=30),
                    )
                    st.rerun()
                else:
                    st.error("Incorrect code. Please check your email and try again.")
            if st.button("Use a different email", type="secondary"):
                st.session_state.otp_sent = False
                st.rerun()
        st.markdown("</div>", unsafe_allow_html=True)
    st.stop()